---
# system wide
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      ignore_errors: yes
      changed_when: False
  vars_files:
    - vars.yml
  tasks:
#    - {include_tasks: tasks/packages.yml, tags: ['packages', 'apt']}
    #- {include_tasks: tasks/homebrew.yml, tags: ['brew_install']}
    #- {include_tasks: tasks/i3.yml, tags: ['i3', 'packages']}
#    - {include_tasks: tasks/samba.yml, tags: ['samba']}

# user specific
- hosts: localhost
  ignore_errors: yes
  connection: local
  become: yes
  become_user: "{{user}}"
  roles:
    - role: evandam.conda
  vars_files:
    - vars.yml
  tasks:
    #- {include_tasks: tasks/dotfiles.yml, tags: ['dotfiles']}
    #- {include_tasks: tasks/homebrew_packages.yml, tags: ['brew', 'packages']}
    - {include_tasks: tasks/cheat.yml, tags: ['cheat']}
    #- {include_tasks: tasks/miniforge.yml, tags: ['miniforge']}
    #- {include_tasks: tasks/miniforge_packages.yml, tags: ['miniforge', 'packages']}
    #- {include_tasks: tasks/neovim.yml, tags: ['neovim']}
    #- {include_tasks: tasks/aodn_chef.yml, tags: ['aodn', 'chef']}
    #- {include_tasks: tasks/data_services.yml, tags: ['aodn', 'data_services']}
    #- {include_tasks: tasks/fonts.yml, tags: ['fonts']}
    #- {include_tasks: tasks/nextcloud.yml, tags: ['appimages','nextcloud', 'packages']}
    #- {include_tasks: tasks/github_repos.yml, tags: ['github','repos']}
    #- {include_tasks: tasks/mobac.yml, tags: ['mobac']}

# needs other packages to be installed first prior to run the following
- hosts: localhost
  ignore_errors: yes
  connection: local
  become: True
  #become_user: "{{user}}"
  tags: "jetbrains"
  roles:
    - role: webarchitect609.jet_brains_toolbox
  vars_files:
    - vars.yml
