---
# user specific
- hosts: localhost
  connection: local
  become: yes
  become_user: "{{user}}"
  roles:
    - role: evandam.conda
  vars_files:
    - vars.yml
  tasks:
    - {include: tasks/homebrew.yml, tags: ['brew_install']}
    - {include: tasks/homebrew_packages.yml, tags: ['brew', 'packages']}
    - {include: tasks/dotfiles.yml, tags: ['dotfiles']}
    - {include: tasks/cheat.yml, tags: ['cheat']}
    - {include: tasks/conda.yml, tags: ['conda']}
    - {include: tasks/conda_packages.yml, tags: ['conda', 'packages']}
    - {include: tasks/neovim.yml, tags: ['neovim']}
    - {include: tasks/aodn_chef.yml, tags: ['aodn', 'chef']}
    - {include: tasks/data_services.yml, tags: ['aodn', 'data_services']}
    - {include: tasks/fonts.yml, tags: ['fonts']}
    - {include: tasks/nextcloud.yml, tags: ['appimages','nextcloud', 'packages']}
    - {include: tasks/github_repos.yml, tags: ['github','repos']}
