# user specific
- hosts: localhost
  connection: local
  become: yes
  become_user: "{{user}}"
  roles:
    - role: evandam.conda
  vars_files:
    - vars.yml
  tasks:
    - name: Print all tags
      debug:
        msg: "Available tags: {{ ansible_run_tags }}"

    - {include_tasks: tasks/homebrew.yml, tags: ['brew_install']}
    - {include_tasks: tasks/homebrew_packages.yml, tags: ['brew', 'packages']}
    - {include_tasks: tasks/dotfiles.yml, tags: ['dotfiles']}
    - {include_tasks: tasks/cheat.yml, tags: ['cheat']}
    - {include_tasks: tasks/miniforge.yml, tags: ['miniforge']}
    - {include_tasks: tasks/miniforge_packages.yml, tags: ['miniforge', 'packages']}
    - {include_tasks: tasks/neovim.yml, tags: ['neovim']}
    - {include_tasks: tasks/aodn_chef.yml, tags: ['aodn', 'chef']}
    - {include_tasks: tasks/data_services.yml, tags: ['aodn', 'data_services']}
    - {include_tasks: tasks/fonts.yml, tags: ['fonts']}
    - {include_tasks: tasks/nextcloud.yml, tags: ['appimages','nextcloud', 'packages']}
    - {include_tasks: tasks/github_repos.yml, tags: ['github','repos']}
