# user specific
- hosts: localhost
  connection: local
  become: yes
  become_user: "{{user}}"
  roles:
    - role: evandam.conda
  vars_files:
    - vars.yml

tasks:
  - name: Print all tags
    debug:
      msg: "Available tags: {{ ansible_run_tags }}"

  - name: Apply the brew_install tag to the include and to all tasks in homebrew.yml
    include_tasks:
      file: tasks/homebrew.yml
      apply:
        tags: brew_install
    tags: brew_install

  - name: Apply the brew and packages tags to the include and to all tasks in homebrew_packages.yml
    include_tasks:
      file: tasks/homebrew_packages.yml
      apply:
        tags: brew
    tags:
      - brew
      - packages

  - name: Apply the dotfiles tag to the include and to all tasks in dotfiles.yml
    include_tasks:
      file: tasks/dotfiles.yml
      apply:
        tags: dotfiles
    tags: dotfiles

  - name: Apply the cheat tag to the include and to all tasks in cheat.yml
    include_tasks:
      file: tasks/cheat.yml
      apply:
        tags: cheat
    tags: cheat

  - name: Apply the miniforge tag to the include and to all tasks in miniforge.yml
    include_tasks:
      file: tasks/miniforge.yml
      apply:
        tags: miniforge
    tags: miniforge

  - name: Apply the miniforge and packages tags to the include and to all tasks in miniforge_packages.yml
    include_tasks:
      file: tasks/miniforge_packages.yml
      apply:
        tags: miniforge
    tags:
      - miniforge
      - packages

  - name: Apply the neovim tag to the include and to all tasks in neovim.yml
    include_tasks:
      file: tasks/neovim.yml
      apply:
        tags: neovim
    tags: neovim

  - name: Apply the aodn and chef tags to the include and to all tasks in aodn_chef.yml
    include_tasks:
      file: tasks/aodn_chef.yml
      apply:
        tags: aodn
    tags:
      - aodn
      - chef

  - name: Apply the aodn and data_services tags to the include and to all tasks in data_services.yml
    include_tasks:
      file: tasks/data_services.yml
      apply:
        tags: aodn
    tags:
      - aodn
      - data_services

  - name: Apply the fonts tag to the include and to all tasks in fonts.yml
    include_tasks:
      file: tasks/fonts.yml
      apply:
        tags: fonts
    tags: fonts

  - name: Apply the appimages, nextcloud, and packages tags to the include and to all tasks in nextcloud.yml
    include_tasks:
      file: tasks/nextcloud.yml
      apply:
        tags: appimages
    tags:
      - appimages
      - nextcloud
      - packages

  - name: Apply the github and repos tags to the include and to all tasks in github_repos.yml
    include_tasks:
      file: tasks/github_repos.yml
      apply:
        tags: github
    tags:
      - github
      - repos

