- name: create github directory
  become: yes
  become_user: "{{user}}"
  file:
    path: "{{github_repo_dir}}"
    state: directory
    mode: 0775

- name: clone AODN repos "{{item.name}}"
  become: yes
  become_user: "{{user}}"
  git:
    repo: "{{item.url}}"
    dest: "{{github_repo_dir}}/{{item.name}}"
    accept_hostkey: yes
    track_submodules: yes
    clone: yes
    update: no
  with_items:
    - { url: "{{repo_chef_private}}", name: chef-private }
    - { url: "{{repo_cloud_deploy}}", name: cloud-deploy }
    - { url: "{{repo_chef}}", name: chef }
    - { url: "{{repo_imos_toolbox}}", name: imos-toolbox }
  ignore_errors: true

######################
# IMOS TOOLBOX CONDA
######################
- name: create imos-toolbox yaml conda file
  ignore_errors: yes
  copy:
      content: |
        name: "{{conda_imos_toolbox}}"
        channels:
          - conda-forge
          - defaults
        dependencies:
          - cython
          - python=3.6
          - pip
          - pip:
            - docopt
            - boto3
            - botocore
            - gitPython
      dest: "{{ github_repo_dir }}/imos-toolbox/environment.yml"
      backup: yes

- name: create imos-toolbox conda env
  shell: "[[ $({{conda_path}}/condabin/conda env list | cut -d' ' -f1) = *'{{conda_imos_toolbox}}'* ]] && echo '{{conda_imos_toolbox}} conda env already installed' || {{conda_path}}/condabin/conda env create -f environment.yml"
  args:
    executable: /bin/bash
    chdir: "{{github_repo_dir}}/imos-toolbox"
  become: yes
  become_user: "{{ user }}"
  ignore_errors: true

- name: update imos-toolbox conda env
  shell: "{{conda_path}}/condabin/conda env update -f environment.yml"
  args:
    chdir: "{{github_repo_dir}}/imos-toolbox"
  become: yes
  become_user: "{{ user }}"
  ignore_errors: true

######################
# AODNDATA CONDA
######################

- name: create python-aodndata conda yaml
  ignore_errors: yes
  copy:
      content: |
        # An environment file for Project Officers wanted to use Conda rather than
        # virtualenv
        # This is based on scripts/setup_virtualenv.sh and doesn't interfere with the
        # wheel package
        # stage values are "build", "rc", "production"
        # conda env create --file=stage_environment.yml
        # conda env update --file=stage_environment.yml
        name: "{{conda_aodndata}}"
        channels:
          - conda-forge
          - defaults
          - pypi
        dependencies:
          - cython
          - python=3.8
          - cf-units
          - pip
          - pip:
            - numpy>1.19.0
            - --index-url http://imos-artifacts.s3-website-ap-southeast-2.amazonaws.com/repo/pypi/build/
            - --extra-index-url https://pypi.python.org/simple/
            - --trusted-host imos-artifacts.s3-website-ap-southeast-2.amazonaws.com
            - pytest-cov
            - -c constraints.txt
            - -e .
            - -e .[testing]
      dest: "{{aodndata_dir}}/stage_environment.yml"
      backup: yes

- name: create aodndata conda env
  shell: "[[ $({{conda_path}}/condabin/conda env list | cut -d' ' -f1) = *'{{conda_aodndata}}'* ]] && echo '{{conda_aodndata}} conda env already installed' || {{conda_path}}/condabin/conda env create -f stage_environment.yml"
  args:
    executable: /bin/bash
    chdir: "{{aodndata_dir}}"
  become: yes
  become_user: "{{ user }}"
  ignore_errors: true

- name: update aodndata conda env
  shell: "{{conda_path}}/condabin/conda env update -f stage_environment.yml"
  args:
    chdir: "{{aodndata_dir}}"
  become: yes
  become_user: "{{ user }}"
  ignore_errors: true


#################
# ncvue conda
#################
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build

- name: Create temporary file
  ansible.builtin.tempfile:
    state: file
    suffix: .yml
    prefix: conda_ncvue-
  register: tempfile_1

- name: create ncvue yaml conda file
  ignore_errors: yes
  copy:
      content: |
        name: "{{conda_ncvue}}"
        channels:
          - conda-forge
          - defaults
        dependencies:
          - cartopy
          - python=3.9
          - pip
          - pip:
            - ncvue
      dest: "{{ tempfile_1.path }}"
      backup: yes

- name: create imos-toolbox conda env
  shell: "[[ $({{conda_path}}/condabin/conda env list | cut -d' ' -f1) = *'{{conda_ncvue}}'* ]] \
          && echo '{{conda_ncvue}} conda env already installed' || \
          {{conda_path}}/condabin/conda env create -f '{{ tempfile_1.path }}'"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ user }}"
  ignore_errors: true

- name: update ncvue-toolbox conda env
  shell: "{{conda_path}}/condabin/conda env update -f {{ tempfile_1.path }}"
  become: yes
  become_user: "{{ user }}"
  ignore_errors: true

- name: Use the registered var and the file module to remove the temporary file
  ansible.builtin.file:
    path: "{{ tempfile_1.path }}"
    state: absent
  when: tempfile_1.path is defined
