- name: create usr/bin directory
  become: yes
  become_user: "{{user}}"
  file:
    path: "{{user_home}}/usr/bin"
    state: directory
    mode: 0775

- name: download cheat executable
  get_url:
    url: "{{cheat_exe_url}}"
    dest: "{{user_home}}/usr/bin/cheat"

- name: Changing perm of "cheat", adding "+x"
  file: dest="{{user_home}}/usr/bin/cheat" mode=a+x

- name: download tldr executable
  get_url:
    url: "{{tldr_exe_url}}"
    dest: "{{user_home}}/bin/tldr"

- name: Changing perm of "tldr", adding "+x"
  file: dest="{{user_home}}/bin/tldr" mode=a+x

