- name: create src directory
  become: yes
  become_user: "{{user}}"
  file:
    path: "{{github_repo_dir}}/chef/src"
    state: directory
    mode: 0775

- name: clone repo "{{item.name}}"
  become: yes
  become_user: "{{user}}"
  git:
    repo: "{{item.url}}"
    dest: "{{github_repo_dir}}/chef/src/{{item.name}}"
    accept_hostkey: yes
    track_submodules: yes
    key_file: "{{key_file}}"
    depth: 1
    clone: yes
    update: yes
  with_items:
    - { url: "{{repo_data_services}}", name: data-services }
  ignore_errors: true

- name: create data-services conda env
  shell: "{{conda_path}}/condabin/conda env create -f environment.yml"
  args:
    chdir: "{{data_services_dir}}"
  ignore_errors: yes
  become: yes
  become_user: "{{ user }}"
  ignore_errors: true

- name: update data-services conda env
  shell: "{{conda_path}}/condabin/conda env update -f environment.yml"
  args:
    chdir: "{{data_services_dir}}"
  ignore_errors: yes
  become: yes
  become_user: "{{ user }}"
  ignore_errors: true
