- name: create "{{ github_repo_dir }}"
  become: yes
  become_user: "{{user}}"
  file:
    path: "{{github_repo_dir}}"
    state: directory
    mode: 0775

- name: clone repo "{{item.name}}"
  become: yes
  become_user: "{{user}}"
  git:
    repo: "{{item.url}}"
    dest: "{{github_repo_dir}}/{{item.name}}"
    accept_hostkey: yes
    track_submodules: yes
    depth: 1
    clone: yes
    update: no
  with_items:
    - { url: "{{repo_awesome_fonts}}", name: awesome-terminal-fonts }
    - { url: "{{repo_nerd_fonts}}", name: nerd-fonts }
    - { url: "{{repo_powerline}}", name: powerline }

- name: install powerline
  shell: ". {{github_repo_dir}}/powerline/install.sh"
  ignore_errors: yes

- name: install nerd-fonts
  block:
    - name: "create nerd-fonts dir"
      become: yes
      become_user: "{{user}}"
      file:
        path: "{{user_home}}/.local/share/fonts"
        state: directory
        mode: 0775
    - name: install fonts
      get_url:
        url: "{{nerd_font_1_url}}"
        dest: "{{user_home}}/.local/share/fonts/Droid Sans Mono for Powerline Nerd Font Complete.otf"

- name: download and install patched fronts from nerd-fonts
  block:
    - name: create ~/.fonts directory
      become: yes
      become_user: "{{user}}"
      file:
        path: "{{user_home}}/.fonts"
        state: directory
        mode: 0775

    - name: "download patched fonts"
      unarchive:
        src: "{{nerd_patched_fonts_url}}"
        dest: "{{user_home}}/.fonts"
        remote_src: yes

    - name: "install fonts"
      shell: "fc-cache -f -v"
      ignore_errors: yes
