- name: Update homebrew and upgrade all packages
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ user }}/.linuxbrew/bin"
    update_homebrew: yes
    upgrade_all: yes
  become: yes
  become_user: "{{ user }}"
  ignore_errors: yes

- name: "brew install packages"
  become: yes
  become_user: "{{ user }}"
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ user }}/.linuxbrew/bin"
    name: [
      cmake,
      gcc,
      ruby,
      ruby-install,
      act, # github action
      angle-grinder,
      ansible,
      autojump,
      awscli,
      bat,
      coreutils,
      curl,
      croc, # send files p2p
      dfc,
      diff-so-fancy,
      exa,
      # fasd, # no more maintained by homebrew 
      fd,
      fpp,
      freetype, # for python matplotlib
      fzf,
      gcc@5,
      git,
      git-delta,
      gh, # github cli
      # googler, # not maintained
      grc,
      #highlight,
      htop,
      httpie,
      hub,
      lnav,
      lsd,
      mdcat,
      midnight-commander,
      mycli,
      ncdu,
      node,
      #openssh, # in order to have latest version => SetEnv
      p7zip,
      pgcli,
      pyenv,
      pyenv-virtualenv,
      ranger,
      rbenv,
      ripgrep,
      task,
      the_silver_searcher,
      thefuck,
      tig,
      tmux,
      tree,
      urlview,
      vim,
      viu,
      xclip,
      yt-dlp,
      youtube-dl,
      yq,
      zsh
      ]
    state: present
  ignore_errors: yes


- name: "homebrew add tap monkeys-audio"
  shell: "[[ -f /home/linuxbrew/.linuxbrew/bin/brew ]] && /home/linuxbrew/.linuxbrew/bin/brew tap fernandotcl/homebrew-fernandotcl || ([[ -f /home/{{ user }}/.linuxbrew/bin/brew ]] && /home/{{ user }}/.linuxbrew/bin/brew tap fernandotcl/homebrew-fernandotcl)"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ user }}"
  ignore_errors: yes

- name: "homebrew monkeys-audio"
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ user }}/.linuxbrew/bin"
    name: [
      monkeys-audio
      ]
    state: present
  become: yes
  become_user: "{{ user }}"
  ignore_errors: yes
