- name: Update homebrew and upgrade all packages
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ user }}/.linuxbrew/bin"
    update_homebrew: yes
    upgrade_all: yes
  become: yes
  become_user: "{{ user }}"

- name: "brew install packages"
  become: yes
  become_user: "{{ user }}"
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ user }}/.linuxbrew/bin"
    name: [
      cmake,
      gcc,
      ruby,
      ruby-install,
      angle-grinder,
      ansible,
      bat,
      curl,
      dfc,
      exa,
      fasd,
      fd,
      fpp,
      freetype, # for python matplotlib
      fzf,
      git,
      gh, # github cli
      googler,
      highlight,
      htop,
      httpie,
      hub,
      lnav,
      lsd,
      midnight-commander,
      mycli,
      ncdu,
      node,
      #openssh, # in order to have latest version => SetEnv
      p7zip,
      pgcli,
      pyenv,
      pyenv-virtualenv,
      ranger,
      ripgrep,
      task,
      the_silver_searcher,
      thefuck,
      tig,
      tmux,
      urlview,
      vim,
      youtube-dl,
      zsh
      ]
    state: present
  ignore_errors: yes


- name: "homebrew add tap monkeys-audio"
  shell: "[[ -f /home/linuxbrew/.linuxbrew/bin/brew ]] && /home/linuxbrew/.linuxbrew/bin/brew tap fernandotcl/homebrew-fernandotcl || ([[ -f /home/{{ user }}/.linuxbrew/bin/brew ]] && /home/{{ user }}/.linuxbrew/bin/brew tap fernandotcl/homebrew-fernandotcl)"
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ user }}"
  ignore_errors: yes

- name: "homebrew monkeys-audio"
  homebrew:
    path: "/home/linuxbrew/.linuxbrew/bin:/home/{{ user }}/.linuxbrew/bin"
    name: [
      monkeys-audio
      ]
    state: present
  become: yes
  become_user: "{{ user }}"
  ignore_errors: yes
