- name: Install i3 packages
  ignore_errors: yes
  apt:
    name: [
      acpi,
      xautolock,
      alsa-utils,
      dmenu,
      feh,
      fonts-font-awesome,
      gsimplecal,
      i3,
      i3blocks,
      i3lock,
      i3status,
      pcmanfm,
      neofetch,
      redshift,
      rofi,
      rxvt-unicode-256color,
      screen,
      scrot,
      tlp,
      w3m,
      w3m-img,
      xbacklight,
      xdotool,
      xinit,
      xinput,
      xss-lock
      ]

- name: debian - change brightness permissions/ has to be done at each machine boot
  file:
     dest: "{{debian_brightness_path}}"
     owner: root
     group: video
     mode: 0664

- name: install light
  ignore_errors: yes
  apt:
    deb: "{{light_url}}"
    only_upgrade: yes

- name: add user to video group to use light
  user:
     name: "{{user}}"
     shell: /bin/bash
     groups: video
     append: yes
