- name: Install i3 packages
  ignore_errors: yes
  apt:
    name: [
      acpi,
      alsa-utils,
      dmenu,
      feh,
      fonts-font-awesome,
      i3,
      i3blocks,
      i3lock,
      i3status,
      pcmanfm,
      neofetch,
      redshift,
      rofi,
      rxvt-unicode-256color,
      screen,
      scrot,
      tlp,
      xbacklight,
      xdotool,
      xinit,
      xinput
      ]

- name: install light
  ignore_errors: yes
  apt:
    deb: https://github.com/haikarainen/light/releases/download/v1.2/light_1.2_amd64.deb
    only_upgrade: yes


- name: add user to video group to use light
  user:
     name: "{{user}}"
     shell: /bin/bash
     groups: video
     append: yes

- name: debian - change brightness permissions
  file:
     dest: /sys/class/backlight/intel_backlight/brightness
     owner: root
     group: video
     mode: 0664
