---
- name: Install Python packages in default Miniforge environment
  hosts: localhost
  become: yes
  become_user: "{{ user }}"
  tasks:
    - name: Install Python packages using Miniforge pip
      command: "{{ miniforge_path }}/bin/pip3 install {{ item }}"
      loop:
        - passhole
        - i3ipc
        - fontawesome
      ignore_errors: true

