---
- name: Install Python packages in default Miniforge environment
  become: yes
  become_user: "{{ user }}"
  tasks:
    - name: Install Python packages using Miniforge pip
      ansible.builtin.pip:
        executable: pip3
        name: passhole
          #- i3ipc
          #- fontawesome
      ignore_errors: true

