- name: create ~/mobac directory
  become: yes
  become_user: "{{user}}"
  file:
    path: "{{user_home}}/Mobac"
    state: directory
    mode: 0775


- name: Unarchive Mobac that needs to be downloaded (added in 2.0)
  unarchive:
    src: "{{mobac_url}}"
    dest: "{{user_home}}/Mobac"
    remote_src: yes


- name: Changing perm of "Mobac", adding "+x"
  file: dest="{{user_home}}/Mobac/Mobile_Atlas_Creator.jar" mode=a+x

